# PS1: it is a shell prompt string variable that defines text displayed before each command you enter.
# %n: it is used to display the username of the logged-in user.
# %m: it shows the hostname of the system.
# %1~: the %1 part shows the name of the current working directory and the tilde symbol will only be displayed if you are inside your home directory.
# The @ and : symbols were only used for aesthetic purposes.
PS1="%n@%m %1:~/ "

# addd time or any other element to the right corner:
RPROMPT="%F{241}%B%t%b%f"

export LC_ALL="eu_US.UTF-8"
export KUBE_EDITOR="nvim"
export USE_GKE_GCLOUD_AUTH_PLUGIN="true"
export AWS_PAGER=""
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/google-cloud-sdk/bin"

autoload -Uz compinit
compinit

source <(kubectl completion zsh)
source <(flux completion bash)

alias k="kubectl"
alias kgp="kubectl get pods"
alias kgpa="kubectl get pods -A"

alias glogin="gcloud auth login"
