PS1='\[\e[32m\]\u@\h \[\e[34m\]\w \[\e[0m\]\$ '

export EDITOR="vi"

alias ll='ls -lha'
alias gr='grep --color=always -i'
alias free='free -m'
alias df='df -h'
alias myip='curl ifconfig.me; echo'

ncvz () {
  nc -vz "$1" "$2"
}
