bind-key / setw synchronize-panes on
bind-key \\ setw synchronize-panes off
bind-key r source-file ~/.config/tmux/tmux.conf \; display "Tmux configuration file has been successfully reloaded."

unbind %
unbind \"

bind-key _ splitw -v -c "#{pane_current_path}"
bind-key | splitw -h -c "#{pane_current_path}"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.config/tmux/plugins/tpm/tpm'
